version: '3'
services:
  chatbot:
    image: comp7940_lab3_lab4-chatbot
    environment:
      - ACCESS_TOKEN=6295975720:AAHW7zhliJILtZQYHg1EUtAdwDyKVCBbbHU
      - HOST=redis
      - PASSWORD=comp7940passwordlab8
      - REDISPORT=6379
      - USERNAME=default
    entrypoint: ["python", "chatbot.py"]
    depends_on:
      - redis
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["/usr/local/etc/redis/redis.conf"]
