name: Python safety check

on:
  push:
    branches:
      - main

env:
  DEP_PATH: ./requirements.txt
  GITHUB_WORKSPACE: ./

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print path
        run: pwd
      - name: print working path
        run: echo ${GITHUB_WORKSPACE}/${DEP_PATH}
      - name: Check out master
        uses: actions/checkout@master

      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@master